Решены 5 задач 3 модуля
js-tasks-ru/jsbasic-20220418_sergey-bebyakin pull request #4
Opened 2022-05-03 16:33 UTC by MyNameNewPerson

2022-05-10 06:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-14 13:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-18 10:00 UTC, koalex requested changes
Исправить замечание 4-1

2022-05-18 10:00 UTC, koalex commented on 4-module/1-task/index.js
> +makeFriendsList();
Удали строку 11

2022-05-24 18:20 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-05-24 18:20 UTC, closed without merging